Repository devKomori/MovieListApplication, pull requests merged in 2024-08, with the labels that each got.

#22 Implemented BrowseMoviesActivity.
  .idea/other.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/movielistapplication/BrowseMoviesActivity.java
  app/src/main/java/com/example/movielistapplication/Database/DAOS/MovieDao.java
  app/src/main/java/com/example/movielistapplication/Database/DAOS/UserDao.java
  app/src/main/java/com/example/movielistapplication/Database/MovieListDatabase.java
  app/src/main/java/com/example/movielistapplication/Database/MovieListRepository.java
  app/src/main/java/com/example/movielistapplication/MainActivity.java
  app/src/main/java/com/example/movielistapplication/viewholders/MovieListAdapter.java
  app/src/main/java/com/example/movielistapplication/viewholders/MovieListViewHolder.java
  app/src/main/java/com/example/movielistapplication/viewholders/MovieListViewModel.java
  app/src/main/res/layout/activity_browse_movies.xml
  app/src/main/res/layout/movie_item.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: enhancement, to do

#28 Updated API for integration with the RecyclerView and added movie search functionality.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/movielistapplication/BrowseMoviesActivity.java
  app/src/main/java/com/example/movielistapplication/Database/ApiRetrofitClient.java
  app/src/main/java/com/example/movielistapplication/Database/DAOS/MovieDao.java
  app/src/main/java/com/example/movielistapplication/Database/MovieApiData.java
  app/src/main/java/com/example/movielistapplication/Database/MovieApiJsonResponse.java
  app/src/main/java/com/example/movielistapplication/Database/MovieListDatabase.java
  app/src/main/java/com/example/movielistapplication/Database/MovieListRepository.java
  app/src/main/java/com/example/movielistapplication/Database/TMDBRequest.java
  app/src/main/java/com/example/movielistapplication/Database/entities/Movie.java
  app/src/main/java/com/example/movielistapplication/viewholders/MovieListAdapter.java
  app/src/main/java/com/example/movielistapplication/viewholders/MovieListViewHolder.java
  app/src/main/java/com/example/movielistapplication/viewholders/MovieListViewModel.java
  app/src/main/res/drawable/baseline_calendar_month_24.xml
  app/src/main/res/drawable/baseline_close_24.xml
  app/src/main/res/drawable/baseline_language_24.xml
  app/src/main/res/drawable/baseline_search_24.xml
  app/src/main/res/drawable/rate_star_24.xml
  app/src/main/res/drawable/updated_menu_icon.xml
  app/src/main/res/layout/activity_browse_movies.xml
  app/src/main/res/layout/movie_item.xml
  app/src/main/res/menu/logout_menu.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, improvement

#29 Fixed issue with previous landing page implementation.
  app/src/main/java/com/example/movielistapplication/MainActivity.java
Labels: maintenance

#44 Implement UserDaoTest for testing UserDao database operation methods. (Closes #43)
  app/src/androidTest/java/com/example/movielistapplication/Database/DAOS/UserDaoTest.java
  app/src/main/java/com/example/movielistapplication/Database/DAOS/UserDao.java
  app/src/main/java/com/example/movielistapplication/Database/entities/User.java
Labels: feature
